In [1]:
import tensorflow as tf
import numpy as np
import math

Hint: Use dtype=tf.float64 if you want to have same precision as numpy for testing<br>
Hint: You migth wanna use tf.InterativeSession for convenience

1a: Create two random 0-d tensors x and y of any distribution. <br>
Create a TensorFlow object that returns x + y if x > y, and x - y otherwise. <br>
Hint: look up tf.cond() <br>
I do the first problem for you <br>

In [2]:
def task_1a_np(x, y):
    return np.where(x > y, x + y, x - y)

In [3]:
X = tf.placeholder(tf.float64)
Y = tf.placeholder(tf.float64)
out = tf.cond(tf.greater(X, Y), lambda: tf.add(X, Y), lambda: tf.subtract(X, Y))

In [4]:
with tf.Session() as sess:
    for xx, yy in np.random.uniform(size=(50, 2)):
        actual = sess.run(out, feed_dict={X:xx, Y:yy})
        expected = task_1a_np(xx, yy)
        if actual != expected:
            print('Fail')
            # something something
    else:
        print('Success')

Success


1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).<br>
Return x + y if x < y, x - y if x > y, 0 otherwise.<br>
Hint: Look up tf.case().<br>

In [5]:
def task_1b_np(x, y):
    return np.select(condlist=[x < y, x > y],
                     choicelist=[x + y, x - y],
                     default=0)

In [30]:
X = tf.placeholder(tf.float64)
Y = tf.placeholder(tf.float64)

out = tf.case({X < Y: lambda: X + Y, 
               X > Y: lambda: X - Y}, 
              default=lambda: tf.constant(0., dtype=tf.float64), exclusive=True)

with tf.Session() as sess:
    x, y = np.random.uniform(-1, 1, 2)
    print(x, y)
    result = sess.run(out, {X: x, Y: y})
    print(result)

0.532008117782 0.026135116031
0.505873001751


1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] <br>
and y as a tensor of zeros with the same shape as x. <br>
Return a boolean tensor that yields Trues if x equals y element-wise. <br>
Hint: Look up tf.equal(). <br>

In [53]:
def task_1c_np():
    x = np.array([[0, -2, -1], [0, 1, 2]])
    y = np.zeros_like(x)
    return x == y

In [56]:
x = tf.constant([[0, -2, -1], [0, 1, 2]], dtype=tf.float64)
y = tf.zeros(shape=x.shape.as_list(), dtype=tf.float64)
eq = tf.equal(x, y)

with tf.Session() as sess:
    result = sess.run(eq)
    print(result)

[[ True False False]
 [ True False False]]


1d:<br>
Get the indices of elements in x whose values are greater than 30.<br>
Hint: Use tf.where().<br>
Then extract elements whose values are greater than 30.<br>
Hint: Use tf.gather().<br>

In [2]:
def task_1d_np(x):
    return x[x > 30].reshape(-1, 1)

In [61]:
x = tf.placeholder(dtype=tf.float64)
idx_greater_30 = tf.where(x > 30)
greater_30 = tf.gather(x, idx_greater_30)

with tf.Session() as sess:
    result = sess.run(greater_30, {x: [1, 2, 31, 32]})
    print(result)

[[ 31.]
 [ 32.]]


1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,<br>
2, ..., 6<br>
Hint: Use tf.range() and tf.diag().<br>

In [3]:
def task_1e_np():
    return np.diag(np.arange(1, 7))

In [63]:
diag = tf.diag(tf.range(1, 7))

with tf.Session() as sess:
    d = sess.run(diag)
    print(d)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


1f: Create a random 2-d tensor of size 10 x 10 from any distribution.<br>
Calculate its determinant.<br>
Hint: Look at tf.matrix_determinant().<br>

In [4]:
def task_1f_np(x):
    return np.linalg.det(x)

In [74]:
normal = tf.random_normal(shape=[10, 10])

X = tf.placeholder(dtype=tf.float64)
det = tf.matrix_determinant(X)

with tf.Session() as sess:
    A = normal.eval()
    
    print(sess.run(det, {X: A}))
    print(np.linalg.det(A))

-400.25897215
-400.259


1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].<br>
Return the unique elements in x<br>
Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.<br>

In [87]:
def task_1g_np():
    x = [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9]
    _, idx = np.unique(x, return_index=True)
    return np.take(x, sorted(idx))

In [90]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
unique = tf.unique(x)

with tf.Session() as sess:
    y, _ = sess.run(unique)
    
    print(y)
    print(task_1g_np())

[ 5  2  3 10  6  4  1  0  9]
[ 5  2  3 10  6  4  1  0  9]


1h: Create two tensors x and y of shape 300 from any normal distribution,<br>
as long as they are from the same distribution.<br>
Use tf.cond() to return:<br>
- The mean squared error of (x - y) if the average of all elements in (x - y)<br>
  is negative, or<br>
- The sum of absolute value of all elements in the tensor (x - y) otherwise.<br>
Hint: see the Huber loss function in the lecture slides 3.<br>

In [91]:
def task_1h_np(x, y):
    average = np.mean(x - y)
    mse = np.mean((x - y) ** 2)
    asum = np.sum(np.abs(x - y))
    return mse if average < 0 else asum

In [93]:
x = tf.random_normal(shape=[300], mean=20, dtype=tf.float64)
y = tf.random_normal(shape=[300], mean=20, dtype=tf.float64)

X = tf.placeholder(dtype=tf.float64)
Y = tf.placeholder(dtype=tf.float64)

average = tf.reduce_mean(X - Y)
mse = tf.reduce_mean((X - Y) ** 2)
asum = tf.reduce_sum(tf.abs(X - Y))

out = tf.cond(average < 0, lambda: mse, lambda: asum)

with tf.Session() as sess:
    a, b = x.eval(), y.eval()
    
    res = sess.run(out, {X: a, Y: b})
    res_np = task_1h_np(a, b)
    
    print(res)
    print(res_np)

347.197829479
347.197829479
